apiVersion: v1
kind: service
metadata:
  name: service-name
spec:
  type: NodePort
  ports:
    - targetPort: 80 #application's port
      port: 80
      nodePort: 3000 #if we don't provide it takes a valid port in range 30000 to 32767
  selector:
    app: app-name
    type: labels-identifying
  clusterIP: none #when this attribute is set, a headless service is created. i.e) the service will have no IP of it's own but will be used to created IP for other services. Useful to create IPs for pods in stateful sets.