apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  APP_DB_PASSWORD: password123 # this will then be stored in encoded format `echo surya | base64` #to convert to base64
  APP_API_TOKEN: asdfasdf #this will then be stored in encoded format 
