apiVersion: v1
kind: Pod
metadata: 
  name: ubuntu-sleeper-pod
spec: 
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      args: ["10"] #overrides docker CMD
      command: ["sleep2.0"] #overrides docker ENTRYPOINT
