apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate: 
    spec:
      completions: 3
      parallelism: 3
      template: 
        spec: #spec exactly same as pod definition
          containers:
            - name: math
              image: ubuntu
              command: ['expr', '3', '+', '2']
          restartPolicy: Never

# kubectl edit cronjobs/cron-name //edit and update suspend to true to stop a cronjob
