#k8s default behavior is to let the pod live for ever. 
#that is why pod recreates container when it exits

# Some jobs need many pods. 
# Replicaset is used to make sure specified number of pods are running at all times.
# A job is used to run a set of pods to perform a given task to completion.




# k create job job-name --image nginx --dry-run=client -o yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-name
spec:
  completions: 3 #number of pods to run this, the pods run this in sequence
  backoffLimit: 6
  parallelism: 3
  #if 2 pods goes into error, then k8s keeps creating pods until we get 3 success
  template: 
    spec: #spec exactly same as pod definition
      containers:
        - name: math
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never
