#deployments automatically create replicate set, which creates pods
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: surya-deployment
  labels:
    name: surya-app
    language: golang
spec:
  template:
    metadata: #data about the ojbect, like name, label. Value is in the form of dictionary
     name: name-of-object
     labels: #label can have any key value pair, key can be anything
      app: name-of-app
    spec:
      containers:
        - name: nginx-container # '-' before the item indicates that this is the first item in the list
          image: nginx
  replicas: 3
  selector: 
    matchLabels:
      app: name-of-app  #not mandatory field, but tells what pods falls under it, we need to specify this because replica-set can also manage pods that were not created as part of the replica definition