apiVersion: v1
kind: ReplicationController
metadata: 
  name: surya-app
  labels:
    name: surya-app
    language: golang
spec:
  template:
    metadata: #data about the ojbect, like name, label. Value is in the form of dictionary
     name: name-of-object
     labels: #label can have any key value pair, key can be anything
      app: name-of-app
    spec:
      containers:
        - name: nginx-container # '-' before the item indicates that this is the first item in the list
          image: nginx
  replicas: 3