apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sample
spec:
  accessModes:
    - ReadWriteOnce #matches with PV with same access modes
  resources:
    requests:
      storage: 500Mi
  storageClassName: google-storage-class
  persistentVolumeReclaimPolicy: Retain 
  #can also be set as Delete or Recycle that helps k8s know if the PV should be retained,deleted or recycled.
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
